bookstore/apps/catalogue/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('catalogue.views',
    url(r'^$', 'homepage', name='homepage'),
    url(r'^subscribe/$', 'subscribe_email', name='subscribe'),
    url(r'^catalogue/$', 'catalogue', name='catalogue'),
    url(r'^catalogue/tag/(?P<slug>[-\w]+)/$', 'catalogue_by_tag', name='catalogue-by-tag'),
    url(r'^catalogue/(?P<slug>[-\w]+)/$', 'category', name='category-details'),
    url(r'^catalogue/(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$', 'book_details', name='book-details'),
    url(r'^catalogue/(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/order/$', 'book_order', name='book-order'),
)

bookstore/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('catalogue.urls')),
    url(r'^post/(?P<slug>[-\w]+)/$', 'catalogue.views.post_details', name='post-details'),
    url(r'^admin/', include(admin.site.urls)),
    (r'^search/', include('haystack.urls')),
)

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

urlpatterns += patterns('django.contrib.flatpages.views',
    (r'^(?P<url>.*)$', 'flatpage'),
)

bookstore/apps/catalogue/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail import ImageField


class Category(models.Model):
    name = models.CharField(_("Category name"), max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField(_("Description"),
        blank=True, null=True
    )
    position = models.PositiveIntegerField(default=0,
        verbose_name=_("Position")
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ("-position",)

    def __unicode__(self):
        return self.name


class TextLanguage(models.Model):
    language = models.CharField(_("Language"), max_length=255)

    class Meta:
        verbose_name = _("Text language")
        verbose_name_plural = _("Text languages")
        ordering = ('language',)

    def __unicode__(self):
        return self.language


class Publisher(models.Model):
    name = models.CharField(_("Publisher name"), max_length=255)

    class Meta:
        verbose_name = _("Publisher")
        verbose_name_plural = _("Publishers")
        ordering = ('name',)

    def __unicode__(self):
        return self.name


class Tags(models.Model):
    name = models.CharField(_("Tag name"), max_length=255)
    slug = models.SlugField(max_length=255,
        verbose_name=_("Tag slug")
    )

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    def __unicode__(self):
        return self.name

class BindingType(models.Model):
    name = models.CharField(_("Type of binding"), max_length=255)

    class Meta:
        verbose_name = _("Binding type")
        verbose_name_plural = _("Binding types")

    def __unicode__(self):
        return self.name

class ProductManager(models.Manager):
    def active(self):
        return self.get_query_set().filter(is_active=True)


class Product(models.Model):

    AVAILABLE_STATUSES = (
        (0, _('Not available')),
        (1, _('Anticipating product')),
        (2, _('Is available')),
        (3, _('Pre-order'))
    )

    category = models.ForeignKey(Category,
        verbose_name=_("Category")
    )
    extra_category = models.ForeignKey(Category,
        verbose_name=_("Extra category"),
        related_name = 'products_extra',
        blank=True, null=True
    )
    homepage_position = models.PositiveIntegerField(default=0,
        verbose_name=_("Homepage product position")
    )
    category_position = models.PositiveIntegerField(default=0,
        verbose_name=_("Category product position")
    )
    catalogue_position = models.PositiveIntegerField(default=0,
        verbose_name=_("Catalogue product position")
    )
    extra_category_position = models.PositiveIntegerField(default=0,
        verbose_name=_("Extra category product position")
    )

    author = models.CharField(_("Author"), blank=True, null=True,
        max_length=255
    )
    name = models.CharField(_("Product name"),
        max_length=255, blank=True, null=True
    )
    additional_name_info = models.CharField(_("Additional product name info"),
        max_length=255, blank=True, null=True
    )
    catalogue_name = models.CharField(_("Catalogue product name"),
        max_length=255, blank=True, null=True
    )
    slug = models.SlugField(max_length=255, unique=True,
        verbose_name=_("Product slug")
    )
    short_description = models.TextField(_('Short description'),
        blank=True, null=True
    )
    description_url = models.CharField(_("Description URL"),
        blank=True, null=True, max_length=255
    )
    description = models.TextField(_("Description"),
        blank=True, null=True
    )
    publisher = models.ForeignKey(Publisher, blank=True, null=True,
        verbose_name=_("Publisher")
    )
    publish_year = models.PositiveIntegerField(blank=True, null=True,
        verbose_name=_("Publishing year")
    )
    binding_type = models.ForeignKey(BindingType, blank=True, null=True,
        verbose_name=_("Binding type")
    )
    pages = models.PositiveIntegerField(blank=True, null=True,
        verbose_name=_("Number of pages")
    )
    width = models.PositiveIntegerField(blank=True, null=True,
        verbose_name=_("Width")
    )
    height = models.PositiveIntegerField(blank=True, null=True,
        verbose_name=_("Height")
    )
    units = models.CharField(blank=True, null=True,
        max_length=255,
        verbose_name=_("Units"),
        help_text=_("Units for width and height")
    )
    language = models.ForeignKey(TextLanguage, blank=True, null=True,
        verbose_name=_("Text language")
    )
    available_status = models.PositiveIntegerField(
        choices = AVAILABLE_STATUSES,
        default=0,
        verbose_name=_("Availability status")
    )
    tags = models.ManyToManyField(Tags, blank=True, null=True,
        verbose_name=_("Tags"), editable=False
    )

    price = models.DecimalField(blank=True, null=True,
        verbose_name=_("Price"),
        max_digits=8, decimal_places=2
    )
    stock_price = models.DecimalField(blank=True, null=True,
        verbose_name=_("Stock price"),
        max_digits=8, decimal_places=2
    )

    created = models.DateTimeField(auto_now_add=True,
        verbose_name=_("Created date")
    )
    modified = models.DateTimeField(auto_now=True,
        verbose_name=_("Modified date")
    )
    is_active = models.BooleanField(default=True,
        verbose_name=_("Is active")
    )
    catalogue_image = ImageField(upload_to="catalogue/list-images",
        verbose_name=_("Catalogue image"),
        blank=True, null=True
    )
    main_cover_image = ImageField(upload_to="category/covers",
        verbose_name=_("Main cover image"),
        blank=True, null=True
    )
    show_on_main = models.BooleanField(default=False,
        verbose_name=_("Show on main")
    )

    objects = ProductManager()

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        ordering = ("-modified",)

    def __unicode__(self):
        return "%s, %s" % (self.author, self.name  if self.name else '')


class ProductImage(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("Product"))
    image = ImageField(upload_to="products/images",
        verbose_name=_("Image file")
    )
    caption = models.TextField(blank=True, null=True,
        verbose_name=_("Image caption")
    )
    position = models.PositiveIntegerField(_("Image position"), default=0)

    class Meta:
        verbose_name = _("Product image")
        verbose_name_plural = _("Product images")
        ordering = ['position',]

    def __unicode__(self):
        return self.product.name

bookstore/apps/orders/models.py
import random

from django.db import models
from django.utils.translation import ugettext_lazy as _

from catalogue.models import Product

NUMBERS = "0123456789"


def gen_uuid(range=5):
    return ''.join([random.choice(NUMBERS) for i in xrange(range)])

class Order(models.Model):
    uuid = models.CharField(max_length=10, unique=True,
        verbose_name=_("Order unique id")
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    full_name = models.CharField(max_length=255, blank=True, null=True,
        verbose_name=_("Full name")
    )
    email = models.EmailField(blank=True, null=True,
        verbose_name=_("Email")
    )
    phone = models.CharField(max_length=255, blank=True, null=True,
        verbose_name=_("Phone")
    )
    address = models.TextField(blank=True, null=True,
        verbose_name=_("Address")
    )
    comments = models.TextField(blank=True, null=True,
        verbose_name=_("Additional comments")
    )
    was_contacted = models.BooleanField(verbose_name=_("Was contacted"))
    was_delivered = models.BooleanField(verbose_name=_("Was delivered"))

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
        ordering = ("-created",)

    def __unicode__(self):
        return self.uuid

    def save(self, *args, **kwargs):
        if not self.uuid:
            uuid = gen_uuid()
            self.uuid = uuid
        super(Order, self).save(*args, **kwargs)


class OrderItem(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("Product"))
    order = models.ForeignKey(Order, verbose_name=_("Order"))
    quantity = models.PositiveIntegerField(default=1, verbose_name=_("Quantity"))

    class Meta:
        verbose_name = _("Ordering item")
        verbose_name_plural = _("Ordering items")

    def __unicode__(self):
        return "%s - %s" % (self.product.name, self.order.uuid)

bookstore/apps/orders/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Order, OrderItem


class OrderForm(forms.ModelForm):
    full_name = forms.CharField(label="Имя", required=False,
        widget=forms.TextInput(attrs={'data-required': 'false'})
    )
    email = forms.CharField(required=True, label="E-MAIL",
        widget=forms.TextInput(attrs={
            'data-pattern': '^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$',
            'data-required': 'true'}
            )
    )
    phone = forms.CharField(required=True, label="Телефон",
        widget=forms.TextInput(attrs={'data-required': 'true'})
    )

    class Meta:
        model = Order
        exclude = ('uuid', 'was_contacted', 'was_delivered', 'address', 'comments')
        

bookstore/apps/catalogue/views.py
# -*- coding: utf-8 -*-
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.db.models import Q

from django.conf import settings

from .models import Product, Category
from news.models import Post
from subscription.models import Subscription
from orders.forms import OrderForm


def homepage(request):
    products = Product.objects.filter(show_on_main=True).order_by('homepage_position')
    posts = Post.objects.filter(
        is_published=True,
        show_on_main=True
        ).select_related('category')

    data = {
        'products': products,
        'posts': posts
    }

    return render(request, 'index.html', data)


def catalogue(request):
    categories = Category.objects.all()
    data = {
        'products': Product.objects.active().all().order_by('catalogue_position'),
        'categories': categories
    }

    return render(request, 'catalogue.html', data)


def category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.active().filter(Q(category=category) | Q(extra_category=category)).order_by('category_position')
    results = []
    for item in products:
        if item.extra_category == category:
            item.sort_key = item.extra_category_position
        else:
            item.sort_key = item.category_position
        results.append(item)

    products = sorted(results, key=lambda i: i.sort_key)
    data = {
        'categories': Category.objects.all(),
        'category': category,
        'products': products
    }
    return render(request, 'catalogue.html', data)


def catalogue_by_tag(request, slug):
    products = Product.objects.active().filter(tags__slug=slug)
    categories = Category.objects.all()
    if products.count() == 0:
        raise Http404
    data = {
        'products': products,
        'categories': categories
    }
    return render(request, 'catalogue.html', data)

def book_details(request, category_slug, slug):
    try:
        category = Category.objects.get(slug=category_slug)
        product = Product.objects.active().filter(slug=slug, category=category).select_related(
            'category', 'publisher', 'language').prefetch_related('tags')[0]
    except (Category.DoesNotExist, Product.DoesNotExist, IndexError):
        raise Http404

    data = {
        'product': product,
        'category': category
    }
    return render(request, 'book-details.html', data)


ORDER_POPUP_MESSAGE = u"""
    Благодарим за размещение заказа. Наши специалисты свяжутся с Вами в ближайшее время.
"""

CUSTOMER_SUBJECT = u"""Ваш заказ в PhotoArtBook"""
CUSTOMER_MESSAGE_PLAIN = u"""
Спасибо за размещение заказа на нашем сайте. 

Вы заказали: 
%s "%s"
цена %s грн

Заказ находится в процессе обработки. Наши сотрудники свяжутся с Вами в ближайшее время.

С уважением,
команда PhotoArtBook


photoartbook.com.ua
050 1457565
"""

CUSTOMER_MESSAGE_HTML = u"""
Благодарим за размещение заказа на нашем сайте. <br>
 <br>
Вы заказали: <br>
%s "%s" <br>
цена %s грн <br>
 <br>
Заказ находится в процессе обработки. Наши сотрудники свяжутся с Вами в ближайшее время. <br>
<br>
С уважением, <br>
команда PhotoArtBook <br>

 <br> <br>
<img src="http://88.198.31.45:9111/static/img/logo.png"><br>
<a href="http://photoartbook.com.ua/">photoartbook.com.ua</a><br>
050 1457565 <br>
"""


@csrf_exempt
def book_order(request, category_slug, slug):
    from orders.models import OrderItem
    form = OrderForm(request.POST or None)
    try:
        category = Category.objects.get(slug=category_slug)
        product = Product.objects.active().filter(slug=slug, category=category)[0]
    except (Category.DoesNotExist, Product.DoesNotExist):
        raise Http404
    if request.method == "POST" and form.is_valid():
        order = form.save()
        order_item = OrderItem.objects.create(order=order, product=product)
        subject = u"[%s] Новый заказ - %s" % (order.id, product.name)
        message = u"""
            Имя: %s
            Телефон: %s
            E-Mail: %s
            Книга: %s, %s - %s грн
        """ % (
            order.full_name,
            order.phone, order.email,
            product.author,
            product.name,
            product.price
        )
        send_mail(subject, message, settings.DEFAULT_FROM,
            settings.ORDER_MANAGERS, fail_silently=False)

        # send email to customer
        subject, _from, _to = CUSTOMER_SUBJECT, settings.DEFAULT_FROM, order.email
        text_content = CUSTOMER_MESSAGE_PLAIN % (
            product.author,
            product.name,
            product.price
        )
        html_content = CUSTOMER_MESSAGE_HTML % (
            product.author,
            product.name,
            product.price
        )
        msg = EmailMultiAlternatives(subject, text_content, _from, [_to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        return HttpResponse(json.dumps({'message': ORDER_POPUP_MESSAGE}),
            mimetype="application/json")

    data = {
        'form': form,
        'product': product,
        'category': category
    }
    return render(request, 'book-order.html', data)


def search(request):
    data = {}
    return render(request, 'search.html', data)


def post_details(request, slug):
    post = get_object_or_404(Post, slug=slug)
    data = {
        'post': post
    }
    return render(request, 'post-details.html', data)


@csrf_exempt
def subscribe_email(request):
    if request.method == "POST":
        email = request.POST.get('email', None)
        message = u"""Вы ввели неверный email."""
        if email:
            try:
                validate_email( email )
            except ValidationError:
                message = u"""Вы ввели неверный email."""
            else:
                _subscribe, created = Subscription.objects.get_or_create(email=email)

                if created:
                    message = u"""Спасибо. Ваш адрес добавлен в подписку."""
                else:
                    message = u"""Ваш email уже есть в подписке."""
        data = {'message': message}
        return render(request, 'subscribe-page.html', data)
    else:
        return redirect('/')
        

bookstore/apps/news/views.py
# Create your views here.

bookstore/templates/book-details.html
{% extends "base.html" %}{% load i18n thumbnail staticfiles %}

{% block subcategories %}{% endblock subcategories %}

{% block extra_js %}
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1&appId=332821553495964";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<script type="text/javascript" src="{% static "js/vendor/jquery.mousewheel-3.0.6.pack.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery-validate.js" %}"></script>

<script type="text/javascript" charset="utf-8">
$('document').ready(function(){
  $('img[data-cover]').fancybox({
    'autoHeight': true,
    'autoWidth': true,
    'padding': 0,
    'closeClick': true,
    'closeBtn': false,
    'transitionIn': 'elastic',
    'transitionOut': 'elastic',
    'openEffect'  : 'elastic',
    'margin': 15,
    'href': "{{ product.main_cover_image.url }}"
  });
  
});
</script>
{% endblock extra_js %}

{% block content %}
<div class="detail search-wrap">
	<div class="detail-image">
	  <figure>
        {% thumbnail product.main_cover_image  "300" as im %}
           <img data-cover src="{{ im.url }}" alt="{{ product.name }}">
        {% endthumbnail %}
	  </figure>

	  <div class="detail-images cf">
      {% for image in product.productimage_set.all %}
        {% thumbnail image.image "39x39" crop="center" as im %}
            <a  rel="group" class="book-gallery" href="{{ image.image.url }}"><img src="{{ im.url }}"  width="{{ im.width }}" height="{{ im.height }}" alt="{{ product.name }}"></a>
        {% endthumbnail %}
      {% endfor %}
	  </div>
   </div>
			   
   <article>
          <header class="title">
            {% if product.author %}<b>{{ product.author }}</b><br>{% endif %}
            {{ product.name }}{% if product.additional_name_info %}<br>
            <span class="additional-title">{{ product.additional_name_info }}</span>{% endif %}
          </header>
          <p class="desc">{{ product.short_description|linebreaksbr }} {% if product.description  and not product.description_url %}<a href="javascript:;" data-description-show class="collapse"> подробнее</a> {% endif %}
          {% if product.description_url %}<a target="_blank" href="{{ product.description_url }}" class="collapse"> подробнее</a> {% endif %}
          {% if not product.description_url %}
           </p><p class="desc detailed-description">{{ product.description|linebreaksbr }}<a href="javascript:;" data-description-hide  class="collapse"> скрыть</a></p>
          {% endif %}
	  <ul class="detail-list">
		  {% if product.publisher %}<li>издатель: {{ product.publisher.name }}</li>{% endif %}
		  {% if product.publish_year %}<li>год издания: {{ product.publish_year }}</li>{% endif %}
      {% if product.binding_type %}<li>тип обложки: {{ product.binding_type }}</li>{% endif %}
		  {% if product.pages %}<li>количество страниц: {{ product.pages }}</li>{% endif %}
		  {% if product.width and product.height %}<li>размер книги: {{ product.width }} x {{ product.height }} {% if product.units %}{{ product.units }}{% endif %}</li>{% endif %}
		  {% if product.language %}<li>язык текста: {{ product.language.language }}</li>{% endif %}
	  </ul>
	  <p class="price">
      цена: <b {% if product.stock_price %}style="text-decoration: line-through"{% endif %}>{{ product.price|floatformat:"-2" }}  грн</b> {% if product.stock_price %}<b style="color: #6f1030">{{ product.stock_price|floatformat:"-2" }} грн</b>{% endif %}</p>
	  <p class="waiting">{% if product.available_status == 2 %}есть в наличии{% elif product.available_status == 1 %}ожидается поступление{% elif product.available_status == 3 %}предварительный заказ{% else %}нет в наличии{% endif %}</p>
	  <a href="javascript:;" data-load data-url="{% url book-order product.category.slug product.slug %}" class="btn-order" id="show-popup">{% if product.available_status == 2 %}купить{% else %}заказать{% endif %}</a>
	  <div class="tags">
      {# <header>{% trans "теги" %}:</header> #}
      {#       {% for tag in product.tags.all %} #}
      {#         <a href="{% url catalogue-by-tag tag.slug %}">{{ tag.name }}</a> #}
      {#       {% endfor %} #}
      <div id="fb-root"></div>
      <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-send="false" data-layout="button_count" data-width="450" data-show-faces="true"></div>
	  </div>
       </article>
 </div>
 
 <hr>
{% include "subscribe.html" %}
 
 <div id="popup-order" class="popup-container">
 		    <div class="popup-overlay"></div>
 		    <div class="popup-wrap">
          
        </div>
 </div>

        
{% endblock content %}

bookstore/templates/book-order.html
{% load i18n %}
{% load thumbnail i18n staticfiles %}
<a href="javascript:;" class="fancybox-item fancybox-close" title="Close"></a>  
<div>
  <p>ПОЖАЛУЙСТА, ЗАПОЛНИТЕ ФОРМУ ЗАКАЗА</p>
  <form id="order-form" class="order-form" action="{% url book-order product.category.slug product.slug %}" method="post" accept-charset="utf-8">{% csrf_token %}
    <p><label for="id_full_name">ИМЯ</label>{{ form.full_name }}</p>
    <p><label for="id_email">E-MAIL</label>{{ form.email }}</p>
    <p><label for="id_email">Телефон</label>{{ form.phone }}</p>
  <p><input class="btn-order" type="submit" value="{% trans "Отправить заказ" %}"></p>
  </form>
	<p class="info">ЕСЛИ У ВАС ВОЗНИКЛИ ДОПОЛНИТЕЛЬНЫЕ ВОПРОСЫ, ЗВОНИТЕ 050 1457565</p>
  <script type="text/javascript" src="{% static "js/order.js" %}"></script>

</div>

bookstore/templates/catalogue.html
{% extends "base.html" %} {% load i18n thumbnail %}

{% block subcategories %}
<!--<div class="category">
  {% for cat in categories %}
        <a href="{% url category-details cat.slug %}" class="{% if cat.id == category.id%}active{% endif %}">{{ cat.name }}</a>
  {% endfor %}
</div>-->

<div class="category">
<table>
  <tr>
    {% for cat in categories %}
    <td>
          <a href="{% url category-details cat.slug %}" class="{% if cat.id == category.id%}active{% endif %}">{{ cat.name }}</a>
    </td>      
    {% endfor %}
  </tr>
</table>
</div>
{% endblock subcategories %}



{% block content %}

<div class="catalogue cf">
  {% for product in products %}
  		<a href="{% url book-details product.category.slug product.slug %}" class=""> 
              <figure>
                {% thumbnail product.catalogue_image "155x155" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ product.name }}">
                {% endthumbnail %}
                <figcaption>{% if product.author %}<b>{{ product.author }}</b><br>{% endif %}{{ product.catalogue_name|default:"" }}</figcaption>
              </figure>
  	   </a>
  {% endfor %}
</div>

<hr>
{% include "subscribe.html" %}

{% endblock content %}

bookstore/templates/index.html
{% extends "base.html" %}
{% load thumbnail i18n staticfiles %}

{% block subcategories %}{% endblock subcategories %}

{% block content %}
	<div class="main-article banner">
		<ul class="homepage-slider">
      {% for post in  posts %}
            <li class="active" data-article="{{ forloop.counter }}" {% if not forloop.counter == 1 %}style="display:none"{% endif %}>
                {% thumbnail post.image "236x236" crop="center" as im %}
                    {% if post.show_url %}<a href="{{ post.get_url }}"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></a>{% else %}<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">{% endif %}
                {% endthumbnail %}
			  <article>
          {% if post.pre_title_section %}
            <div class="pre-title-section" style="text-transform: uppercase; font-size: 13px">
              {{ post.pre_title_section }}
            </div>
          {% endif %}
          {% if post.title %}
            <div class="title-section" style="font-size: 26px; line-height: 25px;{% if post.pre_title_section %}padding: 2px;{% endif %}">
              {{ post.title }}
            </div>
          {% endif %}
          {% if post.author_section %}
          <div class="author-section" style="font-size: 18px;">
            {{ post.author_section }}
          </div>
          {% endif %}
          {% if post.post_author_section  %}
          <div class="post-autor-section">
            <em style="font-size: 12px;">{{ post.post_author_section }}</em>
          </div>
          {% endif %}
                  <p style="padding-top: 8px; line-height: 1.4">{{ post.banner_content|safe }} {% if post.show_url %}<a class="more" href="{{ post.get_url }}">подробнее</a>{% endif %}</p>
                </article>
            </li>
    {% endfor %}
          </ul>

		<nav class="bullets">
      {% for post in posts %}
		      <a href="javascript:;" class="{% if forloop.first %}active{% endif %}" data-article="{{ forloop.counter }}"></a>
      {% endfor %}
	   </nav>

   </div>
   
   <div class='index-recommend'>
     PhotoArtBook рекомендует
   </div>
            
	<hr>
			
        <div class="catalogue cf" style="margin-top: 31px;">
          {% for product in products %}
          		<a href="{% url book-details product.category.slug product.slug %}" class=""> 
                      <figure>
                        {% thumbnail product.catalogue_image "155x155" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ product.name }}">
                        {% endthumbnail %}
                        <figcaption>{% if product.author %}<b>{{ product.author }}</b><br>{% endif %}{{ product.catalogue_name|default:"" }}</figcaption>
                      </figure>
          	   </a>
          {% endfor %}
        </div>
			
	<hr>
  {% include "subscribe.html" %}
      </div>
    </div>

{% endblock content %}

bookstore/templates/post-details.html
{% extends "base.html" %}
{% load i18n thumbnail %}

{% block subcategories %}{% endblock subcategories %}

{% block content %}
<div class="post search-wrap">
      <img src="{{ post.image.url }}">
   <article>
     <header>
       {{ post.title }}
     </header>
          <p>{{ post.content|linebreaksbr }}</p>
       </article>
 </div>

 <hr>
{% include "subscribe.html" %}
{% endblock content %}

bookstore/templates/subscribe-page.html
{% extends "base.html" %}
{% load i18n thumbnail %}

{% block subcategories %}{% endblock subcategories %}

{% block content %}
<div class="post">
   <article style="margin-left: 52px;"><p>{{ message }}</p></article>
 </div>

 <hr>
{% include "subscribe.html" %}
{% endblock content %}

bookstore/templates/subscribe.html
<form action="{% url subscribe %}" method="post" class="subscribe">
	<label for="subsribe">подписаться</label>
	<input type="text" name="email" value="" placeholder="ваш e-mail" id="subsribe">
  <input type="submit" value="ok">
</form>